/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lel
 */
public class jOperacion extends javax.swing.JFrame {

    /**
     * Creates new form jOperacion
     */
    public jOperacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnNuevo.setEnabled(false);     
    }
    public void calcular(String num1, String num2){



    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfNum1 = new javax.swing.JTextField();
        jtfNum2 = new javax.swing.JTextField();
        jtfSum = new javax.swing.JTextField();
        jtfRes = new javax.swing.JTextField();
        jtfMul = new javax.swing.JTextField();
        jtfDiv = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jlblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operaciones");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Operaciones");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 111, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Primer número:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 37, 108, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Segundo número:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 60, 125, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Resultados");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 79, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Suma:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 240, 60, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Resta:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 240, 50, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 255));
        jLabel7.setText("Multiplicación:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 290, 120, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 204, 0));
        jLabel8.setText("División:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 290, 70, 17);

        jtfNum1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtfNum1);
        jtfNum1.setBounds(120, 60, 50, 20);

        jtfNum2.setForeground(new java.awt.Color(255, 102, 0));
        jtfNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNum2ActionPerformed(evt);
            }
        });
        jPanel1.add(jtfNum2);
        jtfNum2.setBounds(310, 60, 50, 20);

        jtfSum.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jtfSum);
        jtfSum.setBounds(130, 230, 48, 20);

        jtfRes.setForeground(new java.awt.Color(204, 0, 204));
        jPanel1.add(jtfRes);
        jtfRes.setBounds(300, 230, 48, 20);

        jtfMul.setForeground(new java.awt.Color(102, 0, 255));
        jPanel1.add(jtfMul);
        jtfMul.setBounds(130, 290, 48, 20);

        jtfDiv.setForeground(new java.awt.Color(102, 204, 0));
        jPanel1.add(jtfDiv);
        jtfDiv.setBounds(300, 290, 48, 20);

        btnCalcular.setBackground(new java.awt.Color(255, 102, 0));
        btnCalcular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });
        jPanel1.add(btnCalcular);
        btnCalcular.setBounds(150, 130, 79, 23);

        btnNuevo.setBackground(new java.awt.Color(51, 255, 51));
        btnNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(100, 340, 67, 23);

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(240, 340, 59, 23);

        jlblError.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblError.setForeground(new java.awt.Color(255, 0, 0));
        jlblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlblError);
        jlblError.setBounds(10, 79, 353, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNum2ActionPerformed

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
    
    if(jtfNum1.getText().length()==0){
        jlblError.setText("!POR FAVOR INTRODUSCA UN NÚMERO¡");
        btnCalcular.setEnabled(false);
        jtfNum1.requestFocus();
    }else {
        if(jtfNum2.getText().length()==0){
        jlblError.setText("¡POR FAVOR INTRODUSCA UN NÚMERO!");
        btnCalcular.setEnabled(false);
        jtfNum2.requestFocus();
    }else {
    btnCalcular.setEnabled(true);
        
    double n1=Double.parseDouble(jtfNum1.getText());
    double n2=Double.parseDouble(jtfNum2.getText());   
        jtfSum.setText(String.valueOf(n1+n2));
        jtfRes.setText(String.valueOf(n1-n2));    
        jtfMul.setText(String.valueOf(n1*n2));
        jtfDiv.setText(String.valueOf(n1/n2));
        jlblError.setText("");
        btnNuevo.setEnabled(true);
    } 
    }
    }//GEN-LAST:event_btnCalcularMouseClicked

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        jtfSum.setText("");
        jtfRes.setText("");
        jtfMul.setText("");
        jtfDiv.setText("");
        jtfNum1.setText("");
        jtfNum2.setText("");
        jtfNum1.requestFocus();
        btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jOperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblError;
    private javax.swing.JTextField jtfDiv;
    private javax.swing.JTextField jtfMul;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfNum2;
    private javax.swing.JTextField jtfRes;
    private javax.swing.JTextField jtfSum;
    // End of variables declaration//GEN-END:variables
}
